<?php

//Defining constants so code is clearer
#namespace ? {
        const UploadKey = 'avatar';
        const AllowedTypes = ['image/jpeg','image/jpg','image/bmp','image/png'];
          
    
        #use const ?\UploadKey;
        #use const ?\AllowedTypes;

#Session started for storing user details
session_start();



##PROCESSING FORM
#Take user text input and sanitizes
    if(!empty(filter_input_array(INPUT_POST))){//This gets the whole array of Post, no flags therefore default is to not filter - ok as filtering later
                    
                    #could I shorten the below using a loop?
                    $firstname = filter_input(INPUT_POST,'firstname',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);//Remove all HTML tags from a string plus ASCI>127
                    $secondname = filter_input(INPUT_POST,'secondname',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    $lastname   = filter_input(INPUT_POST,'lastname',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    $addresslineone   = filter_input(INPUT_POST,'addresslineone',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    $addresslinetwo   = filter_input(INPUT_POST,'addresslinetwo',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    $city   = filter_input(INPUT_POST,'city',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    $postcode = filter_input(INPUT_POST,'postcode',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    $username= filter_input(INPUT_POST,'username',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    $password = filter_input(INPUT_POST,'password',FILTER_SANITIZE_STRING,FILTER_FLAG_STRIP_HIGH);
                    
                    #generate random customerid here - temporary - will be generated by database in the future
                    $customerID= rand(000, 1000);
            
                    $_SESSION['userDetails']['username'] = $username;
                    $_SESSION['userDetails']['customerID'] = $customerID;
    }
        

#Now Deal with uploaded image - checks no errors and stores in AvatarUploads folder
    #Error checking
    #$errors = array();

    if (empty($_FILES[UploadKey]['name'])){
        header("Location: uploadErrorPage.php"); 
        $_SESSION['errorMessage']="You forgot to add your file!";//stored error message in a storage file so that available to other php pages
        die();
    }

    if ($_FILES[UploadKey]['error'] == (1||2)) {
        #$errors[] ="Your file is too big for us to handle, awkward! Please choose a file under 10MB.";      
        header("Location: uploadErrorPage.php"); 
        $_SESSION['errorMessage']="Your file is too big for us to handle, awkward! Please choose a file under 10MB.";//stored error message in a storage file so that available to other php pages
        die();
        
    }
    
    if (!in_array($_FILES[UploadKey]['type'],AllowedTypes)){//For some reason I had to put this before the file size check, couldn't work out why - even if did a under the limit, but wrong type - i was getting the error message for a wrong size
        #$errors[] = "We only accept .JPEG .PNG and .BMP files I'm afraid";
        header("Location: uploadErrorPage.php"); 
        $_SESSION['errorMessage']="We only accept .JPEG .PNG and .BMP files I'm afraid";//stored error message in a storage file so that available to other php pages
        die();
    }
    
        $tempFileLoc = $_FILES[UploadKey]['tmp_name'];
        $destFileLoc = 'avatarUploads/'.$_SESSION['userDetails']['customerID'].'_'.$_FILES[UploadKey]['name'];
        $_SESSION['userDetails']['avatarLocation']=$destFileLoc;//for use in profile page

    if (file_exists($destFileLoc)) {// Check if file already exists
        #$errors[] ="We've already got this file, thanks though";
        header("Location: uploadErrorPage.php"); 
        $_SESSION['errorMessage']="We've already got this file, thanks though";//stored error message in a storage file so that available to other php pages
        die();
    }

    if ($_FILES[UploadKey]['error']>0){
        #$errors[] = "Unfortunately there's been an error with the uploading process";
        header("Location: uploadErrorPage.php"); 
        $_SESSION['errorMessage']="Unfortunately there's been an error with the uploading process";//stored error message in a storage file so that available to other php pages
        die();
    }
    
//   //if errors were found  
//        if(!empty($errors)){
//            header("Location: uploadErrorPage.php"); 
//            $_SESSION['errorMessage']= $errors; //beware this is now an array and not a single string
//            die();
//        }

    //Moving the file and ensuring deleted from temporary location
        if(!move_uploaded_file($tempFileLoc, $destFileLoc)){//trys to move, if successful returns true therefore if failed, ! would make true and get error statement
            header("Location: uploadErrorPage.php"); 
            $_SESSION['errorMessage']= "There's been an error with the uploading process";
            die();
        }
        else {
            unset($_SESSION['errorMessage']);
            header("Location: profilePage.php");
            //var_dump($_FILES);
            //var_dump($_SESSION); checking to see that errorMessage successfully cleared - yep
        }

        if (file_exists($tempFileLoc)){
            unlink($tempFileLoc);
        }

    #}//closure of namespace

